


FROM public.ecr.aws/lambda/python:3.11

COPY src/miax_13_new_lambda/requirements.txt .
# install dependencies
RUN pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"
# copy the content of the local src directory to the working directory
COPY src\miax_13_new_lambda\app.py ${LAMBDA_TASK_ROOT}
# Run the server
CMD [ "app.handler" ]